 services:
    cobalt:
        image: ghcr.io/imputnet/cobalt:11

        init: true
        read_only: true
        restart: unless-stopped
        container_name: cobalt

        ports:
            - 9000:9000/tcp

        environment:
            API_URL: "http://127.0.0.1:9000"

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    bot:
        image: registry.gitlab.com/kovalssky/telegram-bot-cobalt

        restart: unless-stopped
        container_name: cobalt-bot

        ports:
            - 9000:9000/tcp

        environment:
          # Token from @BotFather
            - TOKEN=

          # URL Cobalt API, no need to change. It will be raised locally.
            - COBALT_API_URL=http://127.0.0.1:9000